In [1]:
import numpy as np 

**NUMPY INDEXING AND SLICING OF VECTORS**

In [55]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [73]:
arr[4]

15

**NUMPY INDEXING AND SLICING OF MATRIX**

In [3]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [107]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [109]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [133]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [135]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [137]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [4]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
col=[0,5]
arr[col]

array([[ 1,  2,  3,  4,  5],
       [26, 27, 28, 29, 30]])

In [15]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
arr[arr>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
arr%3==0

array([[False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [41]:
arr[arr%5==0]

array([ 5, 10, 15, 20, 25, 30])

In [46]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [47]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [7]:
arr2 = np.arange(1,56).reshape(5,5)
arr2

ValueError: cannot reshape array of size 55 into shape (5,5)

In [59]:
np.log(arr2)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582]])

In [60]:
np.mean(arr2)

np.float64(13.0)

In [ ]:
arr2 = np.arange(1,).reshape(5,5)
